spring.application.name=shopvn-register-swing
app.db.url=jdbc:sqlserver://localhost:1433;databaseName=ShopVN;encrypt=true;trustServerCertificate=true
app.db.user=sa
app.db.password=1224454

app.ui.title=ShopVN.vn

spring.main.web-application-type=none
spring.main.headless=false